pipeline {
    agent any
    tools {
        go 'go1.19'
    }
    environment {
        GO114MODULE = 'on'
        CGO_ENABLED = 0 
        GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"
    }
    stages {        
        stage('Pre Test') {
            steps {
                echo 'Installing dependencies'
                sh 'go version'
                sh 'go install golang.org/x/lint/golint@latest'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Compiling and building'
		sh 'go mod init'
                sh 'go build'
            }
        }

        
        
    }
     
}
