pipeline {
    agent any
    tools {
        go 'go1.19'
    }
    environment {
        GO114MODULE = 'on'
        CGO_ENABLED = 0 
       // GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/"
	GOPATH = "$WORKSPACE/"
    }
    stages {        
        stage('Pre Test') {
            steps {
                echo 'Installing dependencies'
                sh 'go version'
                sh 'go get ./...'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Compiling and building'
		sh 'go run main.go'
                
            }
        }

        
        
    }
    }
